version: '3.5'

services:
    nginx:
        build: ./docker/nginx/
        container_name: nginx_test_kubernetes
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf

    php:
        build:
            context: .
            dockerfile: docker/php/Dockerfile
        container_name: php_test_kubernetes
        volumes:
            - .:/usr/src/app
