apiVersion: apps/v1
kind: Deployment
metadata:
    name: nginx
spec:
    replicas: 1
    selector:
        matchLabels:
            service: nginx
    template:
        metadata:
            labels:
                service: nginx
        spec:
            containers:
                - name: nginx
                  image: "unpetitlu/test-nginx"
---
apiVersion: v1
kind: Service
metadata:
    name: nginx
spec:
    type: NodePort
    selector:
        service: nginx
    ports:
        - port: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
    name: nginx
spec:
    rules:
    - host: "myapp.com"
      http:
          paths:
          - path: "/"
            pathType: "Prefix"
            backend:
                  service:
                      name: nginx
                      port:
                          number: 80
